<?php

include_once('os_news_events.features.inc');

/**
 * Implementation of hook_disable().
 */
function os_news_events_disable() {
  $views =  views_get_view('news');
  $views->delete();
}

/**
 * Implementation of hook_theme_registry_alter().
 *
 * @param $theme_registry The entire cache of theme registry information, post-processing.
 */
function os_news_events_theme_registry_alter(&$theme_registry) {
  
  $path = drupal_get_path('module', 'os_news_events').'/templates';
  _theme_process_registry($theme_registry, 'phptemplate', 'theme_engine', 'os_news_events', $path);
  
  //return print_r($theme_registry['views_view']);
}

/**
 * Implementation of phptemplate_preprocess_node().
 *
 * @param $vars
 */
function os_news_events_preprocess_node(&$vars){
  // Check if the display is the teaser for "News"
  if($vars['type'] == 'news'){
    //Replace $submitted with date defined in field_news_date;
    $vars['submitted'] = '<label>Date: </label>'.$vars['field_news_date'][0]['view'];
    if($vars['teaser']){
      //$vars['content'] = print_r($vars['field_news_link']);
      //Replace $node_url to the uploaded filepath if a file is uploaded
      if($vars['field_news_file'][0]['filepath']){
        $vars['node_url'] = $vars['field_news_file'][0]['filepath'];
      }
      //Replace $node_url to the link url if a link is provided
      if($vars['field_news_link'][0]['url']){
        $vars['node_url'] = $vars['field_news_link'][0]['url'];
      }
      //Replace $content with field_summary value
      $vars['content'] = $vars['field_summary'][0]['safe'];
    }
  }
}

/**
 * Implementation of hook_form_alter().
 */
function os_news_events_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['type']) && $form_id == 'news_node_form') {
		$form['#validate'][] = 'os_news_source_validate';
		//$form['#submit'][] = 'os_news_submit';
	}
}

function os_news_submit($form, $form_state){
  $values = $form_state['values'];
  $count = 0;
  if($values['field_news_file'][0]['filepath']) $count++;
  if($values['field_news_link'][0]['url']) $count++;
  if($values['body']) $count++;
  /*if($count != 1){
    drupal_set_message('Please include only either <strong>File</strong> , <strong>Link</strong> or <strong>Content</strong> only', 'error');
    return false;
  }*/
  return print_r($count);
}

function os_news_source_validate($form, $form_state){
  $values = $form_state['values'];
  $count = 0;
  if($values['field_news_file'][0]['filepath']) $count++;
  if($values['field_news_link'][0]['url']) $count++;
  if($values['body']) $count++;
  if($count != 1){
    $msg = 'Please make sure only one out of <strong>File</strong> , <strong>Link</strong> and <strong>Content</strong> is selected';
    //drupal_set_message($message, 'error');
    form_set_error('field_news_file', ' ');
    form_set_error('field_news_link', ' ');
    form_set_error('body', ' ');
    unset($_SESSION['messages']['error']);
    if (form_get_errors()) {
      drupal_set_message($msg, 'error');
    }
    
  }
}